name = "Logopediando Theme"
license = "Apache 2.0"
licenselink = "https://github.com/js2702/logopediando-theme/blob/master/LICENSE.md"
description = "Logopediando Theme"
homepage = "https://github.com/js2702/logopediando-theme"
tags = ["blog", "bootstrap"]
features = ["blog", "bootstrap"]
min_version = 0.18

[author]
  name = "Please"
  homepage = "dont"

# original theme
[original]
  name = "Startbootstrap Clean Blog"
  homepage = "http://startbootstrap.com/template-overviews/clean-blog/"
  repo = "https://github.com/IronSummitMedia/startbootstrap-clean-blog"
